### ISSUE TITLE
Meta Model Overworld

### ISSUE THREAD

**Issue by WuestFlorian** [Gamify-IT/docs#23]
### Current Behavior:
Currently we encounter the problem that we don't have a document which contains the components (Overworld, Areas, Dungeons) and their relationships.

### Expected Behavior:
Create a meta modell (class diagram) which contains the components; describes the relationships and their multiplicities.
Overworld -> Area (Level) -> Dungeon  (Level, optional)
Level -> Task = Minigame

### DoD:
- [ ] A class diagram is creatd
- [ ] Uwe accepted it

### Story Points:
1

**Comment by delvh** [comment]
Replaced by https://github.com/Gamify-IT/issues/issues/38.
