### ISSUE TITLE
Sketch Overworld Design

### ISSUE THREAD

**Issue by WuestFlorian** [Gamify-IT/docs#24]
### Precondition
complete task "Test adaptability of Zelda Tileset" **TODO: link issue**

### Current Behavior:
Currently we encounter the problem that we don't have a sketch of the overworld design

### Expected Behavior:
Create a sketch which contains the five different areas and overall overworld design structures, such as connections between areas.

### DoD:
- [ ]  A sketch exists which is accepted by Uwe.
- [ ]  A rough sketch is enough, see recording 
- [ ] The sketch is review by the overworld team

### Story Points: 3

**Comment by delvh** [comment]
Replaced by https://github.com/Gamify-IT/issues/issues/39
