### ISSUE TITLE
Creating a protocol template

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/docs#6]

**Comment by cdingm** [comment]
Done. Passt das so oder war das anders gemeint?

**Comment by madebyTimo** [comment]
Ja das ist gut. Dankeschön

**Comment by delvh** [comment]
> Done. Passt das so oder war das anders gemeint?

> Ja das ist gut. Dankeschön

Do I spot German in here? Sakrileg!

**Comment by madebyTimo** [comment]
You are totally right. Please forgive this outrage
